polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path("", views.index, name='index'),
    path("ajax-form/", views.sql_form, name='sql_form'),
]

polls/models.py
from django.db import models

# Create your models here.
class Num(models.Model):
    num = models.IntegerField()

polls/forms.py
from django import forms

class NumForm(forms.Form):
    num = forms.IntegerField(label='number1')

polls/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import JsonResponse
from django.template.loader import render_to_string
from . import forms
from django.db import connection

# Create your views here.
def index(request):
    data = {
        'content' : ["hello"]
    }
    return render(request, "index.html", data)

def sql_exeq(query, args):
    rows = None
    print(query, args)
    with connection.cursor() as cursor:
        cursor.execute(query, args) 
        rows = cursor.fetchall()
    return rows

def sql_form(request):
    if request.POST:
        print("sql_form")
        print(request.POST.get('number1'))
        num = request.POST["number1"]
        sql_rslt = sql_exeq("SELECT id FROM members WHERE id < %s", [num])
        #l = [i for i in range(int(num))]
        l = [item[0] for item in sql_rslt]
        print(l)
        data = {
            'items' : l
        }

        htmlcontent = render_to_string("content.html", data, request)
        return JsonResponse({"content" : htmlcontent})

polls/templates/content.html
<h3> hello </h3>
<div class="row justify-content-center align-items-center g-2">

   <!--     --> 
<div class="col-4">
    
<div class="list-group" id="list-tab" role="tablist">
    {% for item in  items%}
     <a class="list-group-item list-group-item-action" id="list-{{item}}-list" data-bs-toggle="list" href="#list-{{item}}" role="tab" aria-controls="list-{{item}}">
        {{ item }}
    </a>
    {% endfor %}
</div>

</div>
   <!--     --> 


<div class="col-8">
        <div class="bg-gray">
    <div class="tab-content" id="nav-tabContent">

    {% for item in  items%}
    <div class="tab-pane fade" id="list-{{item}}" role="tabpanel" aria-labelledby="list-{{item}}-list">

    <div class = "row">
        <div class="col-4">
        <p> this item is {{ item }}</p>
        </div>

   <!-- ---------accordion-area---------     --> 
        <div class="col-8">
            <div class="acc">
            <div class="acc_btn">
                AAA
            </div>
            <div class="acc_next">
                <div class="acc_btn">
               1 
                </div>
                <div class="acc_next">
                <div class="acc_btn">
                2
                </div>
            </div>
            </div>
            </div>
        </div>
  <!-- ---------accordion-area end---------     --> 
    </div>
   <!-- ---------row end---------     --> 
    </div>
    {% endfor %}

    </div>
        </div>
</div>
   <!-- --------col-8 end---------     --> 
</div>
<script>
$(function(){
  //.accordion_oneの中の.accordion_headerがクリックされたら
  $('.acc_btn').click(function(){
    //クリックされた.accordion_oneの中の.accordion_headerに隣接する.accordion_innerが開いたり閉じたりする。
    $(this).next().slideToggle();
    $(this).toggleClass("open");
  });
});
</script>

polls/templates/index.html
<!doctype html>
<html lang="ja">
  {% load static %}
  <head>
    <title>Ajax</title>  
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'a.css' %}" rel="stylesheet">

    <meta name="theme-color" content="#7952b3">

  </head>
  <body>
        <div class="navbar navbar-dark bd-navbar">
          <div class = "container">
          </div>
        </div> 

      <div class="container align-items-center margin-main">
        <div class="row ">
          <div class="col-auto border ">
          <form class= "row g-3 align-items-center" id="ajax-form" action="{% url 'polls:sql_form' %}" method="POST">
              <div class="col-auto center">
                {% csrf_token %}
                word 
              </div>
              
              <div class="col-auto">
              <input class="form-control" type="text" id="number1" required>
              </div>
              
              <div class="col-auto">
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                 終止形 
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" >
                <label class="form-check-label" for="flexRadioDefault2">
                  語幹
                </label>
              </div>
              <div class="form-check">
              </div>
              </div>

              <div class="col-auto">
              <button class="btn btn-primary mb-3" type="submit" >search</button>
              </div>
          </form>
              </div>

              <div class="col-auto border">
          <form class= "row g-3 align-items-center" id="ajax-form2" action="{% url 'polls:sql_form' %}" method="POST">
              <div class="col-auto">
                {% csrf_token %}
                description
              </div>
              
              <div class="col-auto">
              <input class="form-control" type="text" id="number2" required>
              </div>
              
              <div class="col-auto">
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                 指定なし 
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault4" >
                <label class="form-check-label" for="flexRadioDefault2">
                  A
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault4" >
                <label class="form-check-label" for="flexRadioDefault2">
                  B
                </label>
              </div>
              </div>

              <div class="col-auto">
              <button class="btn btn-primary mb-3" type="submit" >search</button>
              </div>
          </form>
              </div>

          <div id="result">
            {% include 'content.html' %}
          </div>
    </main>
      </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'script.js' %}"></script>

    <script>